import React from "react";
import Sidebar from "@/components/Sidebar";
import { i18n, Locale } from "@/config";
import { Footer } from "@/components/Footer";

import "./style.css";

// generateStaticParams 和动态路由一起使用，用于在构建时静态生成路由：在 next build 时会展现
export async function generateStaticParams() {
  return i18n.locales.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: {
    lng: Locale;
  };
}>) {
  return (
    <html lang={lng}>
      <body>
        <div className="container">
          <div className="main">
            <Sidebar lng={lng} />
            <section className="col note-viewer">{children}</section>
          </div>
          <Footer lng={lng} />
        </div>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import classNames from "classnames";
// import "./globals.css";
// import React from "react";
//
// const inter = Inter({ subsets: ["latin"] });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={classNames(inter.className, "app-router-body")}>
//         {children}
//       </body>
//     </html>
//   );
// }
